/* Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

var n = 4000000;
var evenSum = 0;

function fibonacci(value1, value2) {
  var nextVal = value1 + value2;

  if (nextVal > n) {
    return;
  }

  if ((nextVal % 2) === 0) {
    evenSum += nextVal;
  }

  fibonacci(value2, nextVal);
}
fibonacci(1,1);

var body = document.getElementsByTagName('body')[0];
var output = document.createElement('p');
output.innerHTML = 'The sum of the even-valued terms in the Fibonacci sequence whose values don\'t exceed four million is ' + evenSum +', when starting with values 1 and 2.';
body.appendChild(output);